name: Create PDF

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: xu-cheng/latex-action@v3
        with:
          root_file: manuscript.tex
          working_directory: ./manuscript/
      - name: Copy
        run: |
          mkdir out
          cp ./manuscript/manuscript.pdf ./out/manuscript.pdf
      - name: Compress PDF
        uses: jy95/ghostscript-action@v1  
        with:  
            file: './out/manuscript.pdf'  
            output: './out/gist_tutorial.pdf'  
            arbitrary-parameters: '-dCompatibilityLevel=1.4 -dPDFSETTINGS=/printer'
      - uses: actions/upload-artifact@v4
        with:
          name: gist_tutorial
          path: out/gist_tutorial.pdf
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          TOKEN: ${{ secrets.GH_REPO_ACCESS }}
          REPOSITORY-NAME: liedllab/liedllab.github.io
          BRANCH: main
          CLEAN: true
          FOLDER: out
          target-folder: files/gist_tutorial/
          GIT-CONFIG-NAME: vhoer-bot
          GIT-CONFIG-EMAIL: bot@noreply.vhoer.com
